version: "3.3"
services:
  db:
    image: mariadb
    container_name: 'ebook_db'
    volumes:
      - ./sql/initial_scripts:/docker-entrypoint-initdb.d/
    expose:
      - 3306
    environment: 
      MYSQL_ROOT_PASSWORD: root

  webapp:
    depends_on: 
      - db
    build:
      context: website
      dockerfile: Dockerfile
    volumes:
      - ./website/public_html:/var/www/html/
    expose:
      - 80
    ports:
      - "80:80"
      
